### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by danigarciaalva** [vekexasia/android-edittext-validator#21]
Hi, I was looking for where can I change the color and I couldn't find the file. Is possible change the red color?. Thanks for the library. It's awesome!

**Comment by vekexasia** [comment]
Hello there, even if this is possible by modifying your app theme i suggest to use the library coupled with http://developer.android.com/reference/android/support/design/widget/TextInputLayout.html

**Comment by danigarciaalva** [comment]
So Is this fully compatible? I mean, If I do .validate() the will the error be shown in textinputlayout?

**Comment by vekexasia** [comment]
Yes!
Il 05/set/2015 09:56 PM, "Daniel García Alvarado" <notifications@github.com>
ha scritto:

**Comment by BJKarper** [comment]
I ran into this problem.
http://stackoverflow.com/questions/28081900/how-to-customize-edittext-field-in-android-using-appcompat-v721
I'm working on a fix for it, will probably take me a couple days before I can get to it though. Thought I'd bring it to your attention.
