### ISSUE TITLE
password and confirm password match validation

### ISSUE THREAD

**Issue by samkazmi** [vekexasia/android-edittext-validator#38]
How can i compare two fields to have same data? like email and confirm email? password and confirm password

**Comment by vekexasia** [comment]
Hello samkazmi,

there's a validator for that : https://github.com/vekexasia/android-edittext-validator/blob/master/library/src/com/andreabaccega/formedittextvalidator/SameValueValidator.java

You'll need to add it at runtime

**Comment by samkazmi** [comment]
thanks man.....

**Comment by vekexasia** [comment]
No problem, closing

**Comment by AbdulBasitRishi** [comment]
thanks
