### ISSUE TITLE
two column of one has filled validation

### ISSUE THREAD

**Issue by AnnShih** [vekexasia/android-edittext-validator#41]
I just write

public class HasOneFilledValidator extends Validator {
        private final EditText otherEditText;

```
    public HasOneFilledValidator(EditText otherEditText, String errorMessage) {
        super(errorMessage);
        this.otherEditText = otherEditText;
    }

    @Override
    public boolean isValid(EditText editText) {
        return (TextUtils.getTrimmedLength(editText.getText()) > 0 || TextUtils.getTrimmedLength(otherEditText.getText())) > 0;
    }
```

}

and use AA.addValidator(new HasOneFilledValidator(BB, "test"));
but it doen't run isValid...
What did I missed?

**Comment by vekexasia** [comment]
did you call testValidity?

**Comment by AnnShih** [comment]
I celled testValidty but get empty error message instead of the message I want...
What testType should I set?

**Comment by AnnShih** [comment]
I got error_field_must_not_be_empty message but I don't want it check empty for me...
If I use AA.addValidator(new HasOneFilledValidator(BB, "test")) and filled BB, then I will get AA's empty error, but I want one of them has filled can be true.

**Comment by vekexasia** [comment]
Hello @AnnShih did you solve this?
