### ISSUE TITLE
Special Char

### ISSUE THREAD

**Issue by smail2133** [vekexasia/android-edittext-validator#43]
Hi, I receive problem with alphaNumeric type. Germany chars, detect like special chars.
![device-2016-02-11-090718](https://cloud.githubusercontent.com/assets/5464497/12972042/7b951f04-d0aa-11e5-9d35-7f9d9412f460.png)

**Comment by vekexasia** [comment]
Can you try with alphaValidator?

**Comment by smail2133** [comment]
It's address field, must contain characters and numbers. I will try with regular expressions, to take it possible.

**Comment by vekexasia** [comment]
Can you just give a try to alpha and see if the special char is allowed there?
